### PR TITLE
Lesson 2 - Dataframes

### PR DESCRIPTION
**Pull request by ncclementi**
- Closes https://github.com/coiled/dask-engineering/issues/154

- Start drafting the content of lesson 2.

### CODE REVIEW

**Comment by ncclementi** [comment]
@hayesgb I pushed an attempt at some feature engineering. I'm having some issues with some filter queries. I could use some help with that, happy to discuss over the sync.

**Review by hayesgb — COMMENTED** [review]
Nit -- probably need Coiled Clusters, not coiled clusters.

Thought -- Is it worth having you look at the pre-cleaned dataset I'm creating from Prefect and Coiled at some point in the tutorial?  It would demonstrate the impact of well-prepared dataset.

Meta-comment about parquet.
Most data engineers would write a parquet dataset as:  s3://<bucket>/<path>/my_dataset.parquet
rather than using the wildcard.

Probably need a warning about the recency of nullables -- they offer advantages but aren't always well supported.

I would also include a pivot_table that works.  Also missing anything on joins, which is pretty important.

Given that Paul's work is leaning further toward predicting trip duration, might be interesting to include something on that as a teaser for the ML problem.

**Comment by ncclementi** [comment]
> Nit -- probably need Coiled Clusters, not coiled clusters.
👍 

> Thought -- Is it worth having you look at the pre-cleaned dataset I'm creating from Prefect and Coiled at some point in the tutorial? It would demonstrate the impact of well-prepared dataset.

I'm curious how we will connect it with the rest of the narrative. I think showing them the "good data" and not how to get there will defeat the purpose of a lesson. But including all the steps to get there will make the lesson too long. Maybe we can think of this connection as part of a second iteration.  

> Meta-comment about parquet. Most data engineers would write a parquet dataset as: s3:////my_dataset.parquet rather than using the wildcard.

Is `s3:////my_dataset.parquet` a directory?  

Do you mean when writing the data using to_parquet step?`"s3://coiled-datasets/uber-lyft-tlc/", ` this has the files inside with names that are related to the day (we use the `name_file` function to give them a name) They get saved like this:

Screen Shot 2022-12-19 at 12 14 33 PM



> Probably need a warning about the recency of nullables -- they offer advantages but aren't always well supported.

Yes, this content is in my todo list. I also noticed that the columns I'm working with do not have NaN, so I will probably avoid using them for this notebook, but write about them.

> I would also include a pivot_table that works. Also missing anything on joins, which is pretty important.

**pivot table:** I'll add a pivot table that works.
**joins:** I was not able to find a join that made sense for this notebook. We (Greg, Naty and Paul) talked about future work related to geospatial joins for the boroughs and we said we can create more content with this in a separate blog. I think in this lesson extending the work to include the join will make it extensively long. 

> Given that Paul's work is leaning further toward predicting trip duration, might be interesting to include something on that as a teaser for the ML problem.

This makes a lot of sense, I will add something that includes this.

**Comment by ncclementi** [comment]
@hayesgb I think this is really close. I completed the text around the notebook as well as some visualizations.

While addressing your comments I landed in some issues, I can't quite figure how to fix.:

1. I can't get a single pivot table to work. I was trying to do something like:

```python
trip_time_avg = dd.pivot_table(df_small, index="hvfhs_license_num", columns="shared_request_flag",values="trip_time", aggfunc='mean').compute()
```
and I get the following error:

```python-traceback
...
File ~/mambaforge/envs/dask-tutorial/lib/python3.10/site-packages/dask/utils.py:633, in Dispatch.dispatch(self, cls)
    631         self._lazy.pop(toplevel, None)
    632         return self.dispatch(cls)  # recurse
--> 633 raise TypeError(f"No dispatch for {cls}")

TypeError: No dispatch for <class 'dask.dataframe.core.DataFrame'>
```

2. When using nullable dtypes, some groupby aggregations, return NaN values. While without using nullable dtypes this does not happen. I think there is some issues with the `inf` value. I'm not quite sure how to fix this, @jrbourbeau maybe you have a recommendation. 

Is it possible that using nullable dtypes and having inf values is messing things up here?

**Comment by ncclementi** [comment]
Update:
- pivot table example: we were able to get something to work. Thanks James.
- nullable dtypes: I remove the usage of them as it is exposing a bug, I believe the bug comes from pandas, but we are not being consistent with our behavior either. see full report here https://github.com/dask/dask/issues/9778

**Pull request merged**
